### ISSUE TITLE
Ignoring chosen namespace when versioning is enabled.

### ISSUE THREAD

**Issue by AlexSpart** [radon-h2020/radon-gmt#32]
When creating a new service template and the versioning option is enabled, the Namespace set to the service template is by default example.org.tosca.servicetemplates, even if a different one is chosen by the user.

**Comment by FlxB2** [comment]
~Could you provide the content of your `winery.yml` file?~

Edit: the docker setup via https://hub.docker.com/r/opentosca/radon-gmt is used

**Comment by FlxB2** [comment]
Unfortunately, we need more information what you did exactly in order to reproduce the issue.
I tried using the docker setup with the latest image using the browsers Firefox and Chromium but Namespaces work correctly as far as I can see.

Here's the exact sequence of steps I used: 

1.  Start the latest docker image
2.  Open Tosca Management UI
3.  Press "Add new" in "Service Templates" tab
4.  Enter some Name
5.  Check if versioning is enabled (it is by default)
6.  Insert something in the Namespace field
   (optionally I tried changing the default namespace as well)
    6.1  Change default Namespace
    6.2  Press Apply default Namespace
    6.3  Change Namespace again
7.  Press "Add" button

Please let me know if you did anything differently and what type of browser you are using.
If the Problem relates to setting up new default Namespaces please check if your browser saves the new default Namespace in local storage.

**Comment by AlexSpart** [comment]
Hi Felix,

I remember that my tosca model was saved under my custom namespace only if
versioning was disabled.
I use chrome.

we could possibly schedule a meeting to showcase you what's going on my
side if you think it's helpful.

Br,
Alexandros

**Comment by miwurster** [comment]
Fixed by https://github.com/eclipse/winery/pull/511
