### ISSUE TITLE
Properties issues on AwsLambdaFunction node using the latest GMT image.

### ISSUE THREAD

**Issue by AlexSpart** [radon-h2020/radon-gmt#38]
I am testing the latest version of docker image opentosca/radon-gmt,(DIGEST:sha256:14c8963e024e7c26c7e92c8ec339af56a085510cfc68313d02f704f424d27ff4), 
in which GMT is checking the validity of the properties given to a node on the fly, and gives recommendations on the input form and the pre-set constraints. I really like this functionality, but I came up to some problems/bugs using it, which you can find above.

1. User is prompted to input some value within the constraints, but the actual format is not specified. For example the property "memory_range" is of type "range" and i am prompt to input value "in_range-128,3008". I did not manage to input some value that is accepted by GMT. The red graphical warning is always there and my changes are not saved. - see screenshot 1 & 2.

2. User is not allowed to insert null as value.

3. Property "alias" is referenced as NOT required, but it is essential for the successful deployment of resources.

4. Property "env_vars" is referenced as NOT required, but it is essential for the successful deployment of resources. It is impossible to set this property on the GMT interface, as the every input I tried was not accepted. Adding this property manually in the deployment definition .tosca solved the issue (env_vars: null).

5. Property "concurrency" has a default value 0. Trying to change the value from GMT is not accepted once again. When uploading a lambda function with concurrency 0 I experience an error with code `Lambda invocation failed with status: 429`. Changing the concurrency to 1 manually, in the deployment definition .tosca solved the error. Concurrency set to "null" does not deploy.

These are all observations during testing the new GMT and the latest AwsLambdaFunction node. I hope will be helpful to locate bugs more easily.

<img width="294" alt="ss1" src="https://user-images.githubusercontent.com/23174477/92240805-7c4ef380-eebd-11ea-879d-eee89e21e51a.png">
<img width="294" alt="ss2" src="https://user-images.githubusercontent.com/23174477/92240820-7fe27a80-eebd-11ea-9ef4-0edfa5b926cd.png">

**Comment by miwurster** [comment]
Hi @AlexSpart,

see here my answers to your points above:

1. Ranges according to the TOSCA spec must be entered like this `[ 256, 512 ]`
2. You may try to enter `~` which is essentially a the `null` value in YAML. With this version we try to avoid having null values in our service templates, since IMHO there should be either a respective default value or users have to enter such values.
3. I will fix this on the `AwsLambdaFunction` node type by adding the default value `dev`
4. This is an issue. IMHO this should be handled by xOpera such that it returns `null` by default instead of having `null` values inside the template. However, I think we can fix this by setting the default value to `{}` (empty variables). I'll test this and push the fix to particles if it's working.
5. We always use the default value (`0`) in our tests and everything was working as expected. See an example here: [ThumbnailGeneration](https://github.com/radon-h2020/radon-particles/blob/master/servicetemplates/radon.blueprints/ThumbnailGeneration/ServiceTemplate.tosca#L39)

**Comment by miwurster** [comment]
Entering `~` is not working. It seems we should allow to enter `null` as value in the Topology Modeler.

**Comment by miwurster** [comment]
Fixed in one of the next Docker container builds.
